### ISSUE TITLE
caddy.header.-Server: "" needs to be deleted from compose

### ISSUE THREAD

**Issue by arminus** [vrtmrz/self-hosted-livesync-server#1]
With this header set, I get CORS violations. Remove that line and all is fine.

**Comment by vrtmrz** [comment]
Thank you for checking this!
I couldn't it be reproduced, running on x86?
But, it needs to be in a more suitable place. so I moved this into the fallback entry point.
Could you please test it again?

**Comment by arminus** [comment]
I'm afraid that doesn't work either for me (although I have to admit, I don't really know what that -Server directive does).

I'm running this on a free tier Oracle VPS, which is an AMD EPYC 7551 32-Core Processor running Ubuntu 20.04.3 LTS

**Comment by vrtmrz** [comment]
Thank you for testing. but I'm sorry about it.
"-Server" deletes "Server" header from the response, to hide what software serves the website.

I'ｍ also using Oracle VPS but using A1. but the distro is Ubuntu.
`#20~20.04.1-Ubuntu SMP Tue Sep 21 14:20:46 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
So it should be almost the same environment.
Could you please capture the preflight request that has been failed? (Please hide your server name and addresses)

**Comment by arminus** [comment]
Sorry, I'm stupid. The -Server line works now.

**Comment by vrtmrz** [comment]
Oh, never mind!  I'm glad to hear that the compose file works for you!

For future reference, which section should I improve the readme?

**Comment by arminus** [comment]
It's fine for me, but I know too much already to be a good judge ;-)
